kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.env]
PORT = "8080"

[services.development]
run = "cd /home/runner/workspace/artifacts/api-server && python -m uvicorn main:app --reload --host 0.0.0.0 --port 8080 --log-level info"

[services.production]

[services.production.run]
args = ["bash", "-c", "cd /home/runner/workspace/artifacts/api-server && python -m uvicorn main:app --host 0.0.0.0 --port 8080 --log-level info"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
